<?php

namespace Database\Seeders;

use App\Models\Brand;
use App\Models\Car;
use App\Models\CarModel;
use Illuminate\Database\Seeder;

class CarSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cars = [
            [
                'slug' => 'toyota-corolla-cross-hybrid-2021',
                'name' => '2021 Toyota Corolla Cross hybrid -z 2021',
                'brand' => 'Toyota',
                'model' => 'Corolla Cross',
                'year' => 2021,
                'condition' => 'Pre-Owned',
                'category' => 'popular,family',
                'asking_price' => '৳ 37,00,000',
                'price_lakh' => '37 Lakh Tk',
                'daily_price' => '2,500',
                'rating' => '4.9',
                'reviews' => '2,436',
                'passengers' => 5,
                'doors' => 4,
                'type' => 'Auto',
                'ac' => true,
                'location' => 'Dhaka, Bangladesh',
                'views' => 47,
                'published_date' => '27 Nov, 2023',
                'tag' => 'Verified',
                'main_image' => '/images/corolla-cross-1.jpg',
                'is_featured' => true,
                'photos' => [
                    ['src' => '/images/corolla-cross-1.jpg', 'thumb' => '/images/corolla-cross-1.jpg', 'title' => 'Front 3/4 Studio View'],
                    ['src' => '/images/corolla-cross-2.jpg', 'thumb' => '/images/corolla-cross-2.jpg', 'title' => 'Rear Angle View'],
                    ['src' => '/images/corolla-cross-3.jpg', 'thumb' => '/images/corolla-cross-3.jpg', 'title' => 'Interior Dashboard & Steering'],
                    ['src' => '/images/hero-car.jpg', 'thumb' => '/images/hero-car.jpg', 'title' => 'Full Side Profile'],
                    ['src' => '/images/corolla-cross-1.jpg', 'thumb' => '/images/corolla-cross-1.jpg', 'title' => 'Front Elevation'],
                ],
                'key_specifications' => [
                    ['label' => 'Year', 'value' => '2021'],
                    ['label' => 'Condition', 'value' => 'Pre-Owned'],
                    ['label' => 'Engine', 'value' => '1800 cc'],
                    ['label' => 'Fuel Type', 'value' => 'Hybrid'],
                    ['label' => 'Body Type', 'value' => 'SUV'],
                    ['label' => 'Drive / Wheel', 'value' => '2WD'],
                    ['label' => 'Mileage', 'value' => '24,000 km'],
                    ['label' => 'Transmission', 'value' => 'Automatic'],
                    ['label' => 'Color', 'value' => 'Pearl White'],
                    ['label' => 'Interior', 'value' => 'Black Leather'],
                    ['label' => 'Registration', 'value' => '2021 (Dhaka)'],
                    ['label' => 'Grade / Spec', 'value' => 'Z Package'],
                ],
                'headline' => 'Pre-Owned Toyota Corolla Cross 2021 - Super Fresh Condition, Ready for Delivery',
                'description' => 'Get the elite experience of travel with this 2021 Toyota Corolla Cross Z Hybrid in immaculate condition. Equipped with a fuel-efficient 1800 cc Hybrid Engine and Smooth Automatic Transmission, wrapped in pristine Pearl White exterior with luxury black interior.',
                'highlights' => [
                    ['type' => 'feature', 'title' => 'Key Features', 'text' => 'Panoramic Sunroof, Leather Seats, 360-degree Bird Eye Camera, Toyota Safety Sense (TSS) with Pre-Collision System, Radar Cruise Control, Lane Departure Alert (LDA).'],
                    ['type' => 'tech', 'title' => 'Convenience & Tech', 'text' => 'Push Start, Smart Keyless Entry, Dual-Zone Digital Climate Control, 9-inch Multimedia Display with Apple CarPlay & Android Auto, LED Headlamps & DRL.'],
                    ['type' => 'condition', 'title' => 'Physical Condition', 'text' => '100% original paint, genuine 24,000 km mileage, zero accidental history, verified auction grade 4.5/A.'],
                    ['type' => 'document', 'title' => 'Documentation', 'text' => 'All papers up-to-date (Tax token, Fitness up to 2025/2026), first-party ownership, immediate name transfer possible.'],
                ],
                'equipment_list' => [
                    [
                        'category' => 'Safety & Security',
                        'items' => [
                            'Toyota Safety Sense (TSS 2.0)',
                            'Pre-Collision System (PCS)',
                            'Lane Departure Alert (LDA) with Steering Assist',
                            'Radar Cruise Control (Dynamic)',
                            '360° Panoramic Bird Eye Camera',
                            'Blind Spot Monitoring (BSM)',
                            '8 SRS Airbags System',
                            'Anti-lock Braking System (ABS) with EBD',
                            'Vehicle Stability Control (VSC)',
                            'Rear Cross Traffic Alert (RCTA)',
                            'Front & Rear Parking Sensors',
                            'Anti-theft Engine Immobilizer',
                        ],
                    ],
                    [
                        'category' => 'Comfort & Interior',
                        'items' => [
                            'Push Button Start & Smart Keyless Entry',
                            'Dual-Zone Automatic Climate Control',
                            '9-inch Touchscreen Infotainment Display',
                            'Apple CarPlay & Android Auto Support',
                            'Premium Black Leather Upholstery',
                            '8-way Power Adjustable Driver Seat',
                            'Heated Front Seats',
                            'Tilt & Telescopic Steering Wheel',
                            'Steering-Mounted Audio Controls',
                            'Rear AC Vents & USB Fast Chargers',
                            'Hands-Free Power Backdoor',
                            'Ambient Interior Illumination',
                        ],
                    ],
                    [
                        'category' => 'Exterior & Lighting',
                        'items' => [
                            'Panoramic Sunroof / Moonroof',
                            'Full Bi-Beam LED Headlamps',
                            'LED Daytime Running Lights (DRL)',
                            'LED Front Fog Lamps & Tail Lights',
                            '18-inch Two-Tone Alloy Wheels',
                            'Power Folding Heated Side Mirrors',
                            'Aerodynamic Roof Rails',
                            'Rear Privacy Glass & UV Cut Glass',
                            'Shark Fin Antenna',
                            'Rear Window Defogger with Timer',
                        ],
                    ],
                ],
                'seller' => [
                    'name' => 'SHOHAG LOGIN',
                    'role' => 'Verified Dealer',
                    'location' => 'Dhaka Metro',
                    'phone' => '+880 1712-345678',
                    'rating' => '4.9',
                    'reviewsCount' => 42,
                    'memberSince' => '2021',
                ],
            ],
            [
                'slug' => 'jaguar-xe-l-p250',
                'name' => '2022 Jaguar XE L P250 Luxury Sedan',
                'brand' => 'Jaguar',
                'model' => 'XE L P250',
                'year' => 2022,
                'condition' => 'Pre-Owned',
                'category' => 'luxury,popular',
                'asking_price' => '৳ 48,00,000',
                'price_lakh' => '48 Lakh Tk',
                'daily_price' => '1,800',
                'rating' => '4.8',
                'reviews' => '2,436',
                'passengers' => 4,
                'doors' => 4,
                'type' => 'Auto',
                'ac' => true,
                'location' => 'Gulshan, Dhaka',
                'views' => 68,
                'published_date' => '15 Jan, 2024',
                'tag' => 'Featured',
                'main_image' => '/images/hero-car.jpg',
                'is_featured' => true,
                'photos' => [
                    ['src' => '/images/hero-car.jpg', 'thumb' => '/images/hero-car.jpg', 'title' => 'Front Three Quarter Profile'],
                    ['src' => '/images/hero-car.png', 'thumb' => '/images/hero-car.png', 'title' => 'Studio Side Profile'],
                    ['src' => '/images/audi-car.jpg', 'thumb' => '/images/audi-car.jpg', 'title' => 'Interior Cockpit & Console'],
                    ['src' => '/images/bmw-car.jpg', 'thumb' => '/images/bmw-car.jpg', 'title' => 'Rear Executive Styling'],
                    ['src' => '/images/hero-car.jpg', 'thumb' => '/images/hero-car.jpg', 'title' => 'Full Exterior Angle'],
                ],
                'key_specifications' => [
                    ['label' => 'Year', 'value' => '2022'],
                    ['label' => 'Condition', 'value' => 'Pre-Owned'],
                    ['label' => 'Engine', 'value' => '2000 cc Turbo'],
                    ['label' => 'Fuel Type', 'value' => 'Octane'],
                    ['label' => 'Body Type', 'value' => 'Sedan'],
                    ['label' => 'Drive / Wheel', 'value' => 'RWD'],
                    ['label' => 'Mileage', 'value' => '19,000 km'],
                    ['label' => 'Transmission', 'value' => '8-Speed Auto'],
                    ['label' => 'Color', 'value' => 'Fuji White'],
                    ['label' => 'Interior', 'value' => 'Tan Windsor Leather'],
                    ['label' => 'Registration', 'value' => '2022 (Dhaka)'],
                    ['label' => 'Grade / Spec', 'value' => 'R-Dynamic P250'],
                ],
                'headline' => 'British Luxury & Dynamic Performance — 2022 Jaguar XE L P250 in Mint Condition',
                'description' => 'Experience British sophistication and spirited performance with this pristine 2022 Jaguar XE L P250. Powered by an Ingenium 2.0L Turbocharged Petrol engine delivering 250 HP with seamless 8-speed automatic transmission. Packed with luxury appointments and modern tech.',
                'highlights' => [
                    ['type' => 'feature', 'title' => 'Performance', 'text' => 'Ingenium 2.0L Turbocharged 250 HP engine, 0-100 km/h in 6.5s, JaguarDrive Control with Dynamic, Comfort, and Eco modes.'],
                    ['type' => 'tech', 'title' => 'Luxury Cabin', 'text' => 'Windsor perforated leather seats with 14-way electric adjustment & memory, Meridian 380W Premium Surround Sound System, dual touchscreens.'],
                    ['type' => 'condition', 'title' => 'Condition', 'text' => 'Showroom condition, scratchless Fuji White paint, single-owner executive driven, driven only 19,000 genuine km.'],
                    ['type' => 'document', 'title' => 'Documents', 'text' => 'BRTA registered with Dhaka Metro serial, token and fitness up to 2026, warranty inspection verified.'],
                ],
                'equipment_list' => [
                    [
                        'category' => 'Safety & Security',
                        'items' => [
                            'Autonomous Emergency Braking (AEB)',
                            'Lane Keep Assist with Driver Condition Monitor',
                            'Front and Rear Parking Sensors with 360 Camera',
                            'Dynamic Stability Control (DSC)',
                            'Emergency Brake Assist (EBA)',
                            '6 Airbags (Front, Side & Full Length Curtain)',
                            'Pedestrian Protection Active Bonnet',
                            'Tyre Pressure Monitoring System (TPMS)',
                        ],
                    ],
                    [
                        'category' => 'Comfort & Interior',
                        'items' => [
                            'Touch Pro Duo Dual Touchscreens',
                            'Interactive Digital Driver Display (12.3-inch)',
                            'Meridian Premium Sound System with 11 Speakers',
                            'Configurable Ambient Interior Lighting',
                            'Dual-Zone Climate Control with Cabin Air Ionisation',
                            'Keyless Entry with Push Button Start',
                            'Heated & Cooled Electric Memory Seats',
                            'Wireless Smartphone Charging Pad',
                        ],
                    ],
                    [
                        'category' => 'Exterior & Lighting',
                        'items' => [
                            'Premium LED Headlights with Signature DRL',
                            '18-inch Diamond Turned Alloy Wheels',
                            'Gloss Black Exterior Styling Pack',
                            'Power Folding Auto-Dimming Heated Side Mirrors',
                            'Electric Tilt & Slide Panoramic Sunroof',
                            'Chrome Dual Exhaust Tips',
                        ],
                    ],
                ],
                'seller' => [
                    'name' => 'AUTO SALON BANGLADESH',
                    'role' => 'Premium Luxury Dealer',
                    'location' => 'Gulshan 2, Dhaka',
                    'phone' => '+880 1819-234567',
                    'rating' => '4.8',
                    'reviewsCount' => 38,
                    'memberSince' => '2020',
                ],
            ],
            [
                'slug' => 'audi-r8',
                'name' => '2021 Audi R8 V10 Performance Coupe',
                'brand' => 'Audi',
                'model' => 'R8 V10',
                'year' => 2021,
                'condition' => 'Certified Pre-Owned',
                'category' => 'luxury',
                'asking_price' => '৳ 1,85,00,000',
                'price_lakh' => '1.85 Crore Tk',
                'daily_price' => '2,100',
                'rating' => '4.6',
                'reviews' => '1,936',
                'passengers' => 2,
                'doors' => 2,
                'type' => 'Auto',
                'ac' => true,
                'location' => 'Banani, Dhaka',
                'views' => 112,
                'published_date' => '02 Feb, 2024',
                'tag' => 'Supercar',
                'main_image' => '/images/audi-car.jpg',
                'is_featured' => true,
                'photos' => [
                    ['src' => '/images/audi-car.jpg', 'thumb' => '/images/audi-car.jpg', 'title' => 'Aggressive Front View'],
                    ['src' => '/images/hero-car.jpg', 'thumb' => '/images/hero-car.jpg', 'title' => 'Side Aerodynamic Profile'],
                    ['src' => '/images/bmw-car.jpg', 'thumb' => '/images/bmw-car.jpg', 'title' => 'Rear Diffuser & Exhaust'],
                    ['src' => '/images/corolla-cross-3.jpg', 'thumb' => '/images/corolla-cross-3.jpg', 'title' => 'Racing Cockpit & Controls'],
                    ['src' => '/images/audi-car.jpg', 'thumb' => '/images/audi-car.jpg', 'title' => 'High-Res Studio View'],
                ],
                'key_specifications' => [
                    ['label' => 'Year', 'value' => '2021'],
                    ['label' => 'Condition', 'value' => 'Certified'],
                    ['label' => 'Engine', 'value' => '5200 cc V10'],
                    ['label' => 'Fuel Type', 'value' => 'Octane 98'],
                    ['label' => 'Body Type', 'value' => 'Supercar Coupe'],
                    ['label' => 'Drive / Wheel', 'value' => 'Quattro AWD'],
                    ['label' => 'Mileage', 'value' => '14,000 km'],
                    ['label' => 'Transmission', 'value' => '7-Speed S-Tronic'],
                    ['label' => 'Color', 'value' => 'Suzuka Gray'],
                    ['label' => 'Interior', 'value' => 'Fine Nappa Leather'],
                    ['label' => 'Registration', 'value' => '2021 (Dhaka)'],
                    ['label' => 'Grade / Spec', 'value' => 'Performance 602 HP'],
                ],
                'headline' => 'Naturally Aspirated V10 Masterpiece — 2021 Audi R8 Performance Quattro',
                'description' => 'The pinnacle of Audi Sport engineering: the 2021 Audi R8 V10 Performance Coupe. Housing a legendary 5.2L naturally aspirated V10 producing an exhilarating 602 horsepower and an intoxicating 8,700 RPM redline. Delivered with Quattro all-wheel drive, carbon ceramic brakes, and Suzuka Gray finish.',
                'highlights' => [
                    ['type' => 'feature', 'title' => 'Raw Supercar Power', 'text' => '5.2-liter naturally aspirated V10 with 602 HP, 0-100 km/h in 3.1 seconds, top speed of 331 km/h.'],
                    ['type' => 'tech', 'title' => 'Motorsport Tech', 'text' => 'Carbon ceramic brakes with silver calipers, Audi magnetic ride adaptive suspension, sport exhaust system.'],
                    ['type' => 'condition', 'title' => 'Interior Luxury', 'text' => 'Audi Virtual Cockpit (12.3-inch), Bang & Olufsen 13-speaker 3D Sound System, diamond-stitched Nappa sport seats.'],
                    ['type' => 'document', 'title' => 'Verification', 'text' => '100% genuine 14,000 km, verified Audi maintenance records, non-accidental guarantee.'],
                ],
                'equipment_list' => [
                    [
                        'category' => 'Safety & Track Systems',
                        'items' => [
                            'Carbon Ceramic High-Performance Brakes',
                            'Audi Magnetic Ride Adaptive Dampers',
                            'Quattro Permanent All-Wheel Drive with Mechanical Diff',
                            'Launch Control Mode',
                            'Electronic Stability Control with Sport Mode',
                            'Front and Rear Parking Radar with Reversing Camera',
                            'Full Advanced Multi-Airbag Restraint System',
                        ],
                    ],
                    [
                        'category' => 'Interior & Cockpit',
                        'items' => [
                            'Monoposto Driver Cockpit Architecture',
                            'Flat-Bottom R8 Performance Steering Wheel with Start Button',
                            'Bang & Olufsen 550W Audio System with Headrest Speakers',
                            'Audi Virtual Cockpit with G-Force & Lap Timer Display',
                            'Carbon Fiber Interior Inlays & Trim',
                            'Full Fine Nappa Leather with Contrast Stitching',
                            'Dual-Zone Automatic Climate Control',
                        ],
                    ],
                    [
                        'category' => 'Exterior & Aerodynamics',
                        'items' => [
                            'Audi Laser Light Technology with LED Headlamps',
                            'Carbon Fiber Exterior Mirror Caps & Side Blades',
                            '20-inch 5-Double-Spoke Dynamic Design Wheels',
                            'Active Carbon Rear Spoiler',
                            'Sport Exhaust with Dual Oval Black Tailpipes',
                        ],
                    ],
                ],
                'seller' => [
                    'name' => 'ELITE MOTORS DHAKA',
                    'role' => 'Supercar Specialist',
                    'location' => 'Banani, Dhaka',
                    'phone' => '+880 1711-987654',
                    'rating' => '5.0',
                    'reviewsCount' => 56,
                    'memberSince' => '2019',
                ],
            ],
            [
                'slug' => 'bmw-m3',
                'name' => '2022 BMW M3 Competition xDrive',
                'brand' => 'BMW',
                'model' => 'M3 Competition',
                'year' => 2022,
                'condition' => 'Pre-Owned',
                'category' => 'popular,luxury',
                'asking_price' => '৳ 1,35,00,000',
                'price_lakh' => '1.35 Crore Tk',
                'daily_price' => '1,600',
                'rating' => '4.5',
                'reviews' => '2,036',
                'passengers' => 4,
                'doors' => 4,
                'type' => 'Auto',
                'ac' => true,
                'location' => 'Uttara, Dhaka',
                'views' => 94,
                'published_date' => '10 Feb, 2024',
                'tag' => 'M Power',
                'main_image' => '/images/bmw-car.jpg',
                'is_featured' => true,
                'photos' => [
                    ['src' => '/images/bmw-car.jpg', 'thumb' => '/images/bmw-car.jpg', 'title' => 'Iconic M Kidney Grille & Stance'],
                    ['src' => '/images/bmw-car.png', 'thumb' => '/images/bmw-car.png', 'title' => 'Side Muscular Profile'],
                    ['src' => '/images/hero-car.jpg', 'thumb' => '/images/hero-car.jpg', 'title' => 'Rear Quad M Exhaust'],
                    ['src' => '/images/corolla-cross-3.jpg', 'thumb' => '/images/corolla-cross-3.jpg', 'title' => 'M Carbon Bucket Seats'],
                    ['src' => '/images/bmw-car.jpg', 'thumb' => '/images/bmw-car.jpg', 'title' => 'Full Studio View'],
                ],
                'key_specifications' => [
                    ['label' => 'Year', 'value' => '2022'],
                    ['label' => 'Condition', 'value' => 'Pre-Owned'],
                    ['label' => 'Engine', 'value' => '3000 cc Twin-Turbo'],
                    ['label' => 'Fuel Type', 'value' => 'Octane'],
                    ['label' => 'Body Type', 'value' => 'Sports Sedan'],
                    ['label' => 'Drive / Wheel', 'value' => 'M xDrive AWD'],
                    ['label' => 'Mileage', 'value' => '16,000 km'],
                    ['label' => 'Transmission', 'value' => '8-Speed M Steptronic'],
                    ['label' => 'Color', 'value' => 'Isle of Man Green'],
                    ['label' => 'Interior', 'value' => 'Kyalami Orange / Black'],
                    ['label' => 'Registration', 'value' => '2022 (Dhaka)'],
                    ['label' => 'Grade / Spec', 'value' => 'Competition (503 HP)'],
                ],
                'headline' => 'The Ultimate Driving Machine — 2022 BMW M3 Competition xDrive 503 HP',
                'description' => 'Immaculate 2022 BMW M3 Competition G80 xDrive in striking Isle of Man Green metallic with Kyalami Orange leather interior. Powered by the high-revving S58 3.0L M TwinPower Turbo inline 6-cylinder delivering 503 HP to all four wheels via M xDrive.',
                'highlights' => [
                    ['type' => 'feature', 'title' => 'Motorsport Engine', 'text' => 'S58 3.0L Twin-Turbo Inline-6 with 503 HP, 650 Nm torque, 0-100 km/h in 3.4 seconds.'],
                    ['type' => 'tech', 'title' => 'M xDrive System', 'text' => 'Switchable 4WD, 4WD Sport, and pure 2WD Rear-Wheel Drive drift mode with active M Differential.'],
                    ['type' => 'condition', 'title' => 'Carbon Package', 'text' => 'Carbon fiber roof, M Carbon bucket seats, carbon interior trim, M compound brakes.'],
                    ['type' => 'document', 'title' => 'Condition', 'text' => 'Only 16,000 km, fully maintained by authorized dealer, ceramic coated paint, fresh registration.'],
                ],
                'equipment_list' => [
                    [
                        'category' => 'Safety & Driver Assistance',
                        'items' => [
                            'Driving Assistant Professional with Steering & Lane Control',
                            'Active Cruise Control with Stop & Go Function',
                            'Parking Assistant Plus with Surround View Cameras',
                            'M Compound Brakes with Red High-Gloss Calipers',
                            'Head-Up Display (HUD) with M Specific View',
                            'BMW Laserlight with Selective Beam',
                            'Dynamic Stability Control (DSC) with M Dynamic Mode',
                        ],
                    ],
                    [
                        'category' => 'Cockpit & Technology',
                        'items' => [
                            'BMW Live Cockpit Professional with 12.3-inch Display',
                            'Harman Kardon Surround Sound System (16 Speakers)',
                            'M Carbon Bucket Seats with Illuminated M3 Badging',
                            'Wireless Apple CarPlay & Android Auto',
                            '3-Zone Automatic Climate Control',
                            'Comfort Access Keyless System with Digital Key',
                            'Configurable M1 and M2 Red Drive Mode Buttons',
                        ],
                    ],
                    [
                        'category' => 'Exterior & Aerodynamics',
                        'items' => [
                            'M Carbon Fiber Reinforced Plastic (CFRP) Roof',
                            '19"/20" M Double-Spoke Style 826 M Forged Alloy Wheels',
                            'M Sport Exhaust System with Quad Black Chrome Tips',
                            'M Rear Lip Spoiler in Carbon Fiber',
                            'Shadowline Exterior Trim & Mirror Caps',
                        ],
                    ],
                ],
                'seller' => [
                    'name' => 'BAVARIA MOTORS BD',
                    'role' => 'European Car Specialist',
                    'location' => 'Uttara, Dhaka',
                    'phone' => '+880 1912-345678',
                    'rating' => '4.7',
                    'reviewsCount' => 29,
                    'memberSince' => '2021',
                ],
            ],
            [
                'slug' => 'lamborghini-huracan',
                'name' => '2021 Lamborghini Huracán EVO V10',
                'brand' => 'Lamborghini',
                'model' => 'Huracán EVO',
                'year' => 2021,
                'condition' => 'Pre-Owned',
                'category' => 'luxury',
                'asking_price' => '৳ 2,90,00,000',
                'price_lakh' => '2.90 Crore Tk',
                'daily_price' => '2,300',
                'rating' => '4.3',
                'reviews' => '2,236',
                'passengers' => 2,
                'doors' => 2,
                'type' => 'Auto',
                'ac' => true,
                'location' => 'Gulshan, Dhaka',
                'views' => 185,
                'published_date' => '20 Jan, 2024',
                'tag' => 'Exotic Supercar',
                'main_image' => '/images/lamborghini-car.jpg',
                'is_featured' => true,
                'photos' => [
                    ['src' => '/images/lamborghini-car.jpg', 'thumb' => '/images/lamborghini-car.jpg', 'title' => 'Striking Italian Supercar Stance'],
                    ['src' => '/images/audi-car.jpg', 'thumb' => '/images/audi-car.jpg', 'title' => 'Aerodynamic Side Profile'],
                    ['src' => '/images/hero-car.jpg', 'thumb' => '/images/hero-car.jpg', 'title' => 'Rear Center High-Exit Exhaust'],
                    ['src' => '/images/corolla-cross-3.jpg', 'thumb' => '/images/corolla-cross-3.jpg', 'title' => 'Fighter Jet Inspired Cockpit'],
                    ['src' => '/images/lamborghini-car.jpg', 'thumb' => '/images/lamborghini-car.jpg', 'title' => 'Showroom Studio View'],
                ],
                'key_specifications' => [
                    ['label' => 'Year', 'value' => '2021'],
                    ['label' => 'Condition', 'value' => 'Exotic Pre-Owned'],
                    ['label' => 'Engine', 'value' => '5200 cc V10 NA'],
                    ['label' => 'Fuel Type', 'value' => 'Octane 98'],
                    ['label' => 'Body Type', 'value' => 'Supercar Coupe'],
                    ['label' => 'Drive / Wheel', 'value' => 'All-Wheel Drive'],
                    ['label' => 'Mileage', 'value' => '8,500 km'],
                    ['label' => 'Transmission', 'value' => '7-Speed Dual-Clutch'],
                    ['label' => 'Color', 'value' => 'Giallo Inti Yellow'],
                    ['label' => 'Interior', 'value' => 'Nero Ade Alcantara'],
                    ['label' => 'Registration', 'value' => '2021 (Dhaka)'],
                    ['label' => 'Grade / Spec', 'value' => 'EVO AWD (631 HP)'],
                ],
                'headline' => 'Pure Italian Passion & V10 Symphony — 2021 Lamborghini Huracán EVO AWD',
                'description' => 'Sensational 2021 Lamborghini Huracán EVO Coupe in signature Giallo Inti multi-layer metallic pearl yellow with black Alcantara sport interior. Equipped with the legendary 5.2-liter naturally aspirated V10 engine producing 631 HP with all-wheel steering and LDVI predictive dynamics.',
                'highlights' => [
                    ['type' => 'feature', 'title' => 'V10 Power', 'text' => '5.2L Naturally Aspirated V10 unleashing 631 HP, 0-100 km/h in 2.9 seconds, top speed over 325 km/h.'],
                    ['type' => 'tech', 'title' => 'LDVI System', 'text' => 'Lamborghini Dinamica Veicolo Integrata (LDVI) predictive handling system with rear-wheel steering and torque vectoring.'],
                    ['type' => 'condition', 'title' => 'Carbon Ceramic Brakes', 'text' => 'Factory Carbon Ceramic Matrix Brakes with vibrant yellow calipers and Aesir 20-inch wheels.'],
                    ['type' => 'document', 'title' => 'Collector Grade', 'text' => 'Only 8,500 genuine km, flawless condition, imported with full factory paperwork and customs documentation.'],
                ],
                'equipment_list' => [
                    [
                        'category' => 'Performance & Aerodynamics',
                        'items' => [
                            'Lamborghini Dinamica Veicolo Integrata (LDVI) System',
                            'Carbon Ceramic Brakes (CCB) with Monobloc Calipers',
                            'All-Wheel Drive with Electronically Controlled Rear Diff',
                            'Rear-Wheel Steering for Agile Cornering',
                            'MagneRide Magnetorheological Suspension',
                            'Front Axle Lifting System (Protects Underbody)',
                            'Sport Exhaust System with High Center Exit Tips',
                        ],
                    ],
                    [
                        'category' => 'Cockpit & Infotainment',
                        'items' => [
                            '8.4-inch HMI Touchscreen Console with Multi-Finger Gesture',
                            'Full Digital Instrument Cluster with Strada/Sport/Corsa Modes',
                            'Alcantara Sportivo Interior with Contrast Yellow Stitching',
                            'Sensillum Lamborghini Premium Audio System',
                            'Apple CarPlay Smartphone Integration',
                            'Electrochromic Exterior & Interior Rearview Mirrors',
                            'Reversing Camera with Front and Rear Parking Sensors',
                        ],
                    ],
                    [
                        'category' => 'Exterior & Style',
                        'items' => [
                            '20-inch Aesir Diamond-Cut Forged Wheels',
                            'Integrated Aerodynamic Slotted Rear Spoiler',
                            'High Gloss Black Style Package',
                            'Transparent Engine Bonnet with LED Illumination',
                            'Full LED Lighting with Y-Shaped Signature DRL',
                        ],
                    ],
                ],
                'seller' => [
                    'name' => 'PRESTIGE CARS DHAKA',
                    'role' => 'Exotic Auto Gallery',
                    'location' => 'Gulshan 1, Dhaka',
                    'phone' => '+880 1713-112233',
                    'rating' => '4.9',
                    'reviewsCount' => 64,
                    'memberSince' => '2018',
                ],
            ],
            [
                'slug' => 'volvo-xc90-recharge-2023',
                'name' => '2023 Volvo XC90 Recharge Ultimate 7-Seater',
                'brand' => 'Volvo',
                'model' => 'XC90',
                'year' => 2023,
                'condition' => 'Pre-Owned',
                'category' => 'family,luxury',
                'asking_price' => '৳ 95,00,000',
                'price_lakh' => '95 Lakh Tk',
                'daily_price' => '2,200',
                'rating' => '4.9',
                'reviews' => '1,420',
                'passengers' => 7,
                'doors' => 4,
                'type' => 'Auto',
                'ac' => true,
                'location' => 'Gulshan, Dhaka',
                'views' => 52,
                'published_date' => '05 Jan, 2024',
                'tag' => 'Family Choice',
                'main_image' => '/images/volvo-car.jpg',
                'is_featured' => true,
                'photos' => [
                    ['src' => '/images/volvo-car.jpg', 'thumb' => '/images/volvo-car.jpg', 'title' => 'Scandinavian Luxury SUV Stance'],
                    ['src' => '/images/hero-car.jpg', 'thumb' => '/images/hero-car.jpg', 'title' => 'Spacious 7-Passenger Cabin'],
                ],
                'key_specifications' => [
                    ['label' => 'Year', 'value' => '2023'],
                    ['label' => 'Condition', 'value' => 'Pre-Owned'],
                    ['label' => 'Engine', 'value' => '2000 cc Turbo Plug-in Hybrid (455 HP)'],
                    ['label' => 'Fuel Type', 'value' => 'Hybrid / Octane'],
                    ['label' => 'Body Type', 'value' => 'Luxury 7-Seater SUV'],
                    ['label' => 'Drive / Wheel', 'value' => 'AWD Electronic'],
                    ['label' => 'Mileage', 'value' => '12,500 km'],
                    ['label' => 'Transmission', 'value' => '8-Speed Geartronic'],
                    ['label' => 'Color', 'value' => 'Onyx Black Metallic'],
                    ['label' => 'Interior', 'value' => 'Amber Nappa Leather'],
                ],
                'headline' => 'Supreme Family Luxury & World-Class Safety — 2023 Volvo XC90 Ultimate',
                'description' => 'The definitive family luxury SUV. 7 full-sized seats, industry-leading safety tech, Bowers & Wilkins sound, and 455 HP Plug-in Hybrid efficiency.',
                'highlights' => [
                    ['type' => 'feature', 'title' => '7-Passenger Seating', 'text' => 'Three spacious rows of ergonomic seating with multi-zone climate control.'],
                    ['type' => 'tech', 'title' => 'Top Tier Safety', 'text' => 'Volvo City Safety with pedestrian, cyclist, and large animal detection.'],
                ],
                'equipment_list' => [
                    ['category' => 'Safety', 'items' => ['Pilot Assist semi-autonomous drive', '360 Bird Eye Camera', 'Blind Spot Information System']],
                    ['category' => 'Comfort', 'items' => ['Panoramic Sunroof', 'Ventilated & Massaging Seats', 'Bowers & Wilkins High-End Sound']],
                ],
                'seller' => [
                    'name' => 'SCANDINAVIAN MOTORS BD',
                    'role' => 'Certified Dealer',
                    'location' => 'Gulshan 2, Dhaka',
                    'phone' => '+880 1822-445566',
                    'rating' => '4.9',
                    'reviewsCount' => 31,
                    'memberSince' => '2020',
                ],
            ],
            [
                'slug' => 'jeep-wrangler-rubicon-392-2023',
                'name' => '2023 Jeep Wrangler Rubicon 392 V8 4x4',
                'brand' => 'Jeep',
                'model' => 'Wrangler',
                'year' => 2023,
                'condition' => 'Certified Pre-Owned',
                'category' => 'off-road,popular',
                'asking_price' => '৳ 88,00,000',
                'price_lakh' => '88 Lakh Tk',
                'daily_price' => '2,400',
                'rating' => '4.8',
                'reviews' => '1,830',
                'passengers' => 5,
                'doors' => 4,
                'type' => 'Auto',
                'ac' => true,
                'location' => 'Banani, Dhaka',
                'views' => 89,
                'published_date' => '12 Feb, 2024',
                'tag' => 'Trail Rated',
                'main_image' => '/images/jeep-car.jpg',
                'is_featured' => true,
                'photos' => [
                    ['src' => '/images/jeep-car.jpg', 'thumb' => '/images/jeep-car.jpg', 'title' => 'Iconic 4x4 Off-Road Dominance'],
                    ['src' => '/images/hero-car.jpg', 'thumb' => '/images/hero-car.jpg', 'title' => 'Rugged Trail Equipment'],
                ],
                'key_specifications' => [
                    ['label' => 'Year', 'value' => '2023'],
                    ['label' => 'Condition', 'value' => 'Certified Pre-Owned'],
                    ['label' => 'Engine', 'value' => '6400 cc HEMI V8 (470 HP)'],
                    ['label' => 'Fuel Type', 'value' => 'Octane'],
                    ['label' => 'Body Type', 'value' => 'Off-Road 4x4 SUV'],
                    ['label' => 'Drive / Wheel', 'value' => 'Heavy Duty 4WD with Tru-Lok'],
                    ['label' => 'Mileage', 'value' => '11,000 km'],
                    ['label' => 'Transmission', 'value' => '8-Speed TorqueFlite'],
                    ['label' => 'Color', 'value' => 'Hydro Blue Pearl'],
                    ['label' => 'Interior', 'value' => 'Black Leather with Bronze Stitching'],
                ],
                'headline' => 'Unstoppable All-Terrain Legend — 2023 Jeep Wrangler Rubicon 392 HEMI V8',
                'description' => 'Unleash the ultimate off-road conqueror with a 470 HP HEMI V8 engine, FOX performance shocks, electronic sway bar disconnect, and removable roof.',
                'highlights' => [
                    ['type' => 'feature', 'title' => 'Trail-Rated Off-Road', 'text' => 'Heavy-duty Dana 44 axles, Tru-Lok front & rear locking differentials, FOX 2.0 shocks.'],
                    ['type' => 'tech', 'title' => 'HEMI V8 Muscle', 'text' => '6.4L HEMI V8 generating 470 HP and 470 lb-ft torque with active dual-mode exhaust.'],
                ],
                'equipment_list' => [
                    ['category' => 'Off-Road Systems', 'items' => ['Rock-Trac 4:1 Transfer Case', 'Electronic Front Sway Bar Disconnect', '33-inch All-Terrain Tires']],
                    ['category' => 'Cockpit', 'items' => ['Alpine 9-Speaker Audio', 'Waterproof Interior Switches', 'Uconnect 8.4-inch Nav']],
                ],
                'seller' => [
                    'name' => 'OVERLAND 4X4 DHAKA',
                    'role' => 'Off-Road Specialist',
                    'location' => 'Banani, Dhaka',
                    'phone' => '+880 1714-556677',
                    'rating' => '4.8',
                    'reviewsCount' => 45,
                    'memberSince' => '2019',
                ],
            ],
            [
                'slug' => 'ferrari-dino-246-gt-classic',
                'name' => '1974 Ferrari Dino 246 GT Classic Vintage',
                'brand' => 'Ferrari',
                'model' => 'Dino 246 GT',
                'year' => 1974,
                'condition' => 'Vintage Collector',
                'category' => 'vintage,luxury',
                'asking_price' => '৳ 3,50,00,000',
                'price_lakh' => '3.50 Crore Tk',
                'daily_price' => '3,500',
                'rating' => '5.0',
                'reviews' => '980',
                'passengers' => 2,
                'doors' => 2,
                'type' => 'Manual',
                'ac' => true,
                'location' => 'Dhaka Metro',
                'views' => 210,
                'published_date' => '01 Jan, 2024',
                'tag' => 'Vintage Legend',
                'main_image' => '/images/ferrari-car.jpg',
                'is_featured' => true,
                'photos' => [
                    ['src' => '/images/ferrari-car.jpg', 'thumb' => '/images/ferrari-car.jpg', 'title' => 'Iconic Rosso Corsa Body Lines'],
                    ['src' => '/images/hero-car.jpg', 'thumb' => '/images/hero-car.jpg', 'title' => 'Gated Manual Shifter Cockpit'],
                ],
                'key_specifications' => [
                    ['label' => 'Year', 'value' => '1974'],
                    ['label' => 'Condition', 'value' => 'Vintage Collector Grade'],
                    ['label' => 'Engine', 'value' => '2400 cc DOHC V6 (195 HP)'],
                    ['label' => 'Fuel Type', 'value' => 'Octane Vintage'],
                    ['label' => 'Body Type', 'value' => 'Classic Italian Berlinetta'],
                    ['label' => 'Drive / Wheel', 'value' => 'RWD Mid-Engine'],
                    ['label' => 'Mileage', 'value' => '32,000 miles'],
                    ['label' => 'Transmission', 'value' => '5-Speed Gated Manual'],
                    ['label' => 'Color', 'value' => 'Rosso Corsa Red'],
                    ['label' => 'Interior', 'value' => 'Tan Connolly Vintage Leather'],
                ],
                'headline' => 'The Crown Jewel of Automotive History — 1974 Ferrari Dino 246 GT',
                'description' => 'A timeless Pininfarina-sculpted icon. Mid-engine balance, high-revving 2.4L Dino V6 with triple Weber carburetors, and a classic gated 5-speed manual shifter.',
                'highlights' => [
                    ['type' => 'feature', 'title' => 'Collector Status', 'text' => 'Classiche certified, numbers matching chassis and engine, concourse restoration.'],
                    ['type' => 'tech', 'title' => 'Analog Sensation', 'text' => 'Triple Weber 40 DCNF carburetors, 4-wheel independent coil-spring suspension, gated chrome shifter.'],
                ],
                'equipment_list' => [
                    ['category' => 'Vintage Features', 'items' => ['Campagnolo Knock-off Alloy Wheels', 'Connolly Tan Leather Bucket Seats', 'Momo Prototipo Steering Wheel']],
                    ['category' => 'Authentication', 'items' => ['Original Factory Tool Roll & Manuals', 'Ferrari Classiche Red Book', 'Full Historical Provenance']],
                ],
                'seller' => [
                    'name' => 'CLASSIC HERITAGE MOTORS',
                    'role' => 'Vintage Car Curator',
                    'location' => 'Dhaka Diplomatic Zone',
                    'phone' => '+880 1715-998877',
                    'rating' => '5.0',
                    'reviewsCount' => 78,
                    'memberSince' => '2015',
                ],
            ],
            [
                'slug' => 'chevrolet-corvette-stingray-2023',
                'name' => '2023 Chevrolet Corvette Stingray 3LT V8',
                'brand' => 'Chevrolet',
                'model' => 'Corvette',
                'year' => 2023,
                'condition' => 'Certified Pre-Owned',
                'category' => 'luxury,popular',
                'asking_price' => '৳ 1,45,00,000',
                'price_lakh' => '1.45 Crore Tk',
                'daily_price' => '2,800',
                'rating' => '4.9',
                'reviews' => '1,420',
                'passengers' => 2,
                'doors' => 2,
                'type' => 'Auto',
                'ac' => true,
                'location' => 'Gulshan 2, Dhaka',
                'views' => 134,
                'published_date' => '05 Mar, 2024',
                'tag' => 'American Muscle',
                'main_image' => '/images/hero-car.jpg',
                'is_featured' => true,
                'photos' => [
                    ['src' => '/images/hero-car.jpg', 'thumb' => '/images/hero-car.jpg', 'title' => 'Corvette Front View'],
                    ['src' => '/images/hero-car.png', 'thumb' => '/images/hero-car.png', 'title' => 'Corvette Side Profile'],
                ],
                'key_specifications' => [
                    ['label' => 'Year', 'value' => '2023'],
                    ['label' => 'Condition', 'value' => 'Certified Pre-Owned'],
                    ['label' => 'Engine', 'value' => '6.2L LT2 V8 (495 HP)'],
                    ['label' => 'Fuel Type', 'value' => 'Octane'],
                    ['label' => 'Body Type', 'value' => 'Sport Coupe'],
                    ['label' => 'Drive / Wheel', 'value' => 'RWD'],
                    ['label' => 'Mileage', 'value' => '8,500 km'],
                    ['label' => 'Transmission', 'value' => '8-Speed Dual Clutch'],
                    ['label' => 'Color', 'value' => 'Torch Red'],
                    ['label' => 'Interior', 'value' => 'Jet Black Nappa Leather'],
                ],
                'headline' => 'Mid-Engine Mastery — 2023 Chevrolet Corvette Stingray 3LT 495 HP',
                'description' => 'The game-changing mid-engine Chevrolet Corvette Stingray 3LT Coupe. 0-100 in under 3 seconds with dual clutch transmission and Z51 performance package.',
                'highlights' => [
                    ['type' => 'feature', 'title' => 'Z51 Performance', 'text' => 'Brembo performance brakes, performance suspension, electronic limited-slip differential, sport exhaust.'],
                    ['type' => 'tech', 'title' => 'Cockpit Tech', 'text' => 'Bose 14-speaker Performance Series sound, 12-inch digital cluster, GT2 competition seats.'],
                ],
                'equipment_list' => [
                    ['category' => 'Performance', 'items' => ['Z51 Performance Package', 'Dual-Mode Performance Exhaust', 'Magnetic Ride Control 4.0']],
                ],
                'seller' => [
                    'name' => 'USA MOTORS BANGLADESH',
                    'role' => 'American Muscle Specialist',
                    'location' => 'Gulshan 2, Dhaka',
                    'phone' => '+880 1711-223344',
                    'rating' => '4.9',
                    'reviewsCount' => 64,
                    'memberSince' => '2018',
                ],
            ],
            [
                'slug' => 'volkswagen-golf-gti-2023',
                'name' => '2023 Volkswagen Golf GTI Performance Mk8',
                'brand' => 'Volkswagen',
                'model' => 'Golf GTI',
                'year' => 2023,
                'condition' => 'Pre-Owned',
                'category' => 'popular',
                'asking_price' => '৳ 55,00,000',
                'price_lakh' => '55 Lakh Tk',
                'daily_price' => '1,500',
                'rating' => '4.7',
                'reviews' => '1,890',
                'passengers' => 5,
                'doors' => 4,
                'type' => 'Auto',
                'ac' => true,
                'location' => 'Dhanmondi, Dhaka',
                'views' => 88,
                'published_date' => '12 Feb, 2024',
                'tag' => 'Hot Hatch',
                'main_image' => '/images/corolla-cross-2.jpg',
                'is_featured' => true,
                'photos' => [
                    ['src' => '/images/corolla-cross-2.jpg', 'thumb' => '/images/corolla-cross-2.jpg', 'title' => 'Golf GTI Exterior'],
                ],
                'key_specifications' => [
                    ['label' => 'Year', 'value' => '2023'],
                    ['label' => 'Condition', 'value' => 'Pre-Owned'],
                    ['label' => 'Engine', 'value' => '2.0L TSI Turbo (241 HP)'],
                    ['label' => 'Fuel Type', 'value' => 'Octane'],
                    ['label' => 'Body Type', 'value' => 'Compact'],
                    ['label' => 'Drive / Wheel', 'value' => 'FWD with VAQ Limited Slip Diff'],
                    ['label' => 'Mileage', 'value' => '14,000 km'],
                    ['label' => 'Transmission', 'value' => '7-Speed DSG'],
                    ['label' => 'Color', 'value' => 'Kings Red Metallic'],
                    ['label' => 'Interior', 'value' => 'Clark Plaid Sport Cloth'],
                ],
                'headline' => 'The Definitive Hot Hatch — 2023 Volkswagen Golf GTI Mk8',
                'description' => 'Nimble handling, turbo punch, and everyday practicality. The iconic Golf GTI Mk8 delivers 241 HP with lightning-fast DSG dual-clutch shifts.',
                'highlights' => [
                    ['type' => 'feature', 'title' => 'DSG Transmission', 'text' => '7-speed dual-clutch transmission with launch control and steering wheel paddle shifters.'],
                ],
                'equipment_list' => [
                    ['category' => 'Comfort', 'items' => ['Innovision Digital Cockpit', 'Harman Kardon Audio', 'Adaptive Cruise Control']],
                ],
                'seller' => [
                    'name' => 'EUROSTAR AUTOMOBILES',
                    'role' => 'European Specialist',
                    'location' => 'Dhanmondi, Dhaka',
                    'phone' => '+880 1819-556677',
                    'rating' => '4.8',
                    'reviewsCount' => 31,
                    'memberSince' => '2020',
                ],
            ],
            [
                'slug' => 'honda-civic-type-r-2023',
                'name' => '2023 Honda Civic Type R FL5 Turbo',
                'brand' => 'Honda',
                'model' => 'Civic Type R',
                'year' => 2023,
                'condition' => 'Pre-Owned',
                'category' => 'popular,luxury',
                'asking_price' => '৳ 78,00,000',
                'price_lakh' => '78 Lakh Tk',
                'daily_price' => '1,900',
                'rating' => '4.9',
                'reviews' => '2,150',
                'passengers' => 4,
                'doors' => 4,
                'type' => 'Manual',
                'ac' => true,
                'location' => 'Uttara, Dhaka',
                'views' => 165,
                'published_date' => '18 Feb, 2024',
                'tag' => 'Nurburgring Record',
                'main_image' => '/images/bmw-car.jpg',
                'is_featured' => true,
                'photos' => [
                    ['src' => '/images/bmw-car.jpg', 'thumb' => '/images/bmw-car.jpg', 'title' => 'Honda Civic Type R'],
                ],
                'key_specifications' => [
                    ['label' => 'Year', 'value' => '2023'],
                    ['label' => 'Condition', 'value' => 'Pre-Owned'],
                    ['label' => 'Engine', 'value' => '2.0L VTEC Turbo (315 HP)'],
                    ['label' => 'Fuel Type', 'value' => 'Octane'],
                    ['label' => 'Body Type', 'value' => 'Compact'],
                    ['label' => 'Drive / Wheel', 'value' => 'FWD with Helical LSD'],
                    ['label' => 'Mileage', 'value' => '11,000 km'],
                    ['label' => 'Transmission', 'value' => '6-Speed Manual with Rev-Match'],
                    ['label' => 'Color', 'value' => 'Championship White'],
                    ['label' => 'Interior', 'value' => 'Iconic Red Type R Suede'],
                ],
                'headline' => 'Pure Driving Purity — 2023 Honda Civic Type R FL5',
                'description' => 'The ultimate front-wheel drive performance machine. 315 HP VTEC Turbo paired with one of the greatest 6-speed manual transmissions ever built.',
                'highlights' => [
                    ['type' => 'feature', 'title' => 'Track Ready', 'text' => 'Brembo 4-piston front calipers, functional aero wing, dual-axis front suspension.'],
                ],
                'equipment_list' => [
                    ['category' => 'Equipment', 'items' => ['LogR Data Logger', 'Honda Sensing Suite', 'Bose Premium Audio']],
                ],
                'seller' => [
                    'name' => 'NIPPON CARS DHAKA',
                    'role' => 'JDM Specialist',
                    'location' => 'Uttara Sector 3, Dhaka',
                    'phone' => '+880 1714-889900',
                    'rating' => '4.9',
                    'reviewsCount' => 52,
                    'memberSince' => '2017',
                ],
            ],
            [
                'slug' => 'nissan-gt-r-nismo-2022',
                'name' => '2022 Nissan GT-R Nismo Track Edition',
                'brand' => 'Nissan',
                'model' => 'GT-R',
                'year' => 2022,
                'condition' => 'Pre-Owned',
                'category' => 'luxury,popular',
                'asking_price' => '৳ 1,75,00,000',
                'price_lakh' => '1.75 Crore Tk',
                'daily_price' => '2,700',
                'rating' => '4.9',
                'reviews' => '1,980',
                'passengers' => 4,
                'doors' => 2,
                'type' => 'Auto',
                'ac' => true,
                'location' => 'Banani, Dhaka',
                'views' => 210,
                'published_date' => '22 Jan, 2024',
                'tag' => 'Godzilla',
                'main_image' => '/images/audi-car.jpg',
                'is_featured' => true,
                'photos' => [
                    ['src' => '/images/audi-car.jpg', 'thumb' => '/images/audi-car.jpg', 'title' => 'Nissan GT-R Nismo Front'],
                ],
                'key_specifications' => [
                    ['label' => 'Year', 'value' => '2022'],
                    ['label' => 'Condition', 'value' => 'Pre-Owned'],
                    ['label' => 'Engine', 'value' => '3.8L Twin-Turbo V6 (600 HP)'],
                    ['label' => 'Fuel Type', 'value' => 'Octane'],
                    ['label' => 'Body Type', 'value' => 'Sport Coupe'],
                    ['label' => 'Drive / Wheel', 'value' => 'ATTESA E-TS AWD'],
                    ['label' => 'Mileage', 'value' => '9,800 km'],
                    ['label' => 'Transmission', 'value' => '6-Speed Dual Clutch'],
                    ['label' => 'Color', 'value' => 'Stealth Gray'],
                    ['label' => 'Interior', 'value' => 'Recaro Carbon Leather'],
                ],
                'headline' => 'The Legendary Godzilla — 2022 Nissan GT-R Nismo 600 HP',
                'description' => 'Handcrafted by Takumi master engine builders in Yokohama. 600 horsepower, carbon-ceramic brakes, and blistering all-wheel-drive acceleration.',
                'highlights' => [
                    ['type' => 'feature', 'title' => 'Nismo Upgrades', 'text' => 'GT3-spec turbochargers, carbon fiber roof & hood, Bilstein DampTronic suspension.'],
                ],
                'equipment_list' => [
                    ['category' => 'Tech', 'items' => ['Bose Active Noise Cancellation', 'Multi-Function Telemetry Display', 'Titanium Exhaust']],
                ],
                'seller' => [
                    'name' => 'SUPERCAR TRADING BD',
                    'role' => 'Exotic Vehicles',
                    'location' => 'Banani, Dhaka',
                    'phone' => '+880 1712-112233',
                    'rating' => '4.9',
                    'reviewsCount' => 45,
                    'memberSince' => '2019',
                ],
            ],
            [
                'slug' => 'mercedes-benz-s500-limousine-2023',
                'name' => '2023 Mercedes-Benz S500 4MATIC Long Limousine',
                'brand' => 'Mercedes-Benz',
                'model' => 'S-Class',
                'year' => 2023,
                'condition' => 'Certified Pre-Owned',
                'category' => 'luxury,popular',
                'asking_price' => '৳ 2,40,00,000',
                'price_lakh' => '2.4 Crore Tk',
                'daily_price' => '3,200',
                'rating' => '5.0',
                'reviews' => '1,720',
                'passengers' => 5,
                'doors' => 4,
                'type' => 'Auto',
                'ac' => true,
                'location' => 'Gulshan 1, Dhaka',
                'views' => 195,
                'published_date' => '10 Feb, 2024',
                'tag' => 'Executive Flagship',
                'main_image' => '/images/hero-car.jpg',
                'is_featured' => true,
                'photos' => [
                    ['src' => '/images/hero-car.jpg', 'thumb' => '/images/hero-car.jpg', 'title' => 'Mercedes S500 Limousine'],
                ],
                'key_specifications' => [
                    ['label' => 'Year', 'value' => '2023'],
                    ['label' => 'Condition', 'value' => 'Certified Pre-Owned'],
                    ['label' => 'Engine', 'value' => '3.0L Turbo Inline-6 EQ Boost (429 HP)'],
                    ['label' => 'Fuel Type', 'value' => 'Mild Hybrid'],
                    ['label' => 'Body Type', 'value' => 'Limousine'],
                    ['label' => 'Drive / Wheel', 'value' => '4MATIC All-Wheel Drive'],
                    ['label' => 'Mileage', 'value' => '12,000 km'],
                    ['label' => 'Transmission', 'value' => '9G-TRONIC Auto'],
                    ['label' => 'Color', 'value' => 'Obsidian Black Metallic'],
                    ['label' => 'Interior', 'value' => 'Exclusive Sienna Brown Nappa Leather'],
                ],
                'headline' => 'The Pinnacle of First-Class Travel — 2023 Mercedes-Benz S500 Limousine',
                'description' => 'Long wheelbase executive limousine with reclining executive rear seats, hot stone massage, Burmester 3D Surround Sound, and active air suspension.',
                'highlights' => [
                    ['type' => 'feature', 'title' => 'Chauffeur Package', 'text' => 'Executive rear seating with calf rests, twin rear 11.6-inch entertainment screens, panoramic sunroof.'],
                ],
                'equipment_list' => [
                    ['category' => 'Comfort', 'items' => ['AIRMATIC Air Suspension', 'Burmester 3D Surround Sound', 'MBUX Augmented Reality HUD', 'Rear Axle Steering']],
                ],
                'seller' => [
                    'name' => 'PREMIER AUTO BANGLADESH',
                    'role' => 'Flagship Luxury Dealer',
                    'location' => 'Gulshan 1, Dhaka',
                    'phone' => '+880 1811-334455',
                    'rating' => '5.0',
                    'reviewsCount' => 88,
                    'memberSince' => '2016',
                ],
            ],
            [
                'slug' => 'hyundai-tucson-hybrid-2023',
                'name' => '2023 Hyundai Tucson Hybrid HTRAC Crossover',
                'brand' => 'Hyundai',
                'model' => 'Tucson',
                'year' => 2023,
                'condition' => 'Pre-Owned',
                'category' => 'popular,family',
                'asking_price' => '৳ 42,00,000',
                'price_lakh' => '42 Lakh Tk',
                'daily_price' => '1,600',
                'rating' => '4.7',
                'reviews' => '1,640',
                'passengers' => 5,
                'doors' => 4,
                'type' => 'Auto',
                'ac' => true,
                'location' => 'Mirpur, Dhaka',
                'views' => 76,
                'published_date' => '01 Mar, 2024',
                'tag' => 'Parametric Modern',
                'main_image' => '/images/corolla-cross-1.jpg',
                'is_featured' => true,
                'photos' => [
                    ['src' => '/images/corolla-cross-1.jpg', 'thumb' => '/images/corolla-cross-1.jpg', 'title' => 'Hyundai Tucson Hybrid'],
                ],
                'key_specifications' => [
                    ['label' => 'Year', 'value' => '2023'],
                    ['label' => 'Condition', 'value' => 'Pre-Owned'],
                    ['label' => 'Engine', 'value' => '1.6L Turbo Hybrid (226 HP)'],
                    ['label' => 'Fuel Type', 'value' => 'Hybrid'],
                    ['label' => 'Body Type', 'value' => 'Crossover'],
                    ['label' => 'Drive / Wheel', 'value' => 'HTRAC All-Wheel Drive'],
                    ['label' => 'Mileage', 'value' => '18,000 km'],
                    ['label' => 'Transmission', 'value' => '6-Speed Auto'],
                    ['label' => 'Color', 'value' => 'Amazon Gray'],
                    ['label' => 'Interior', 'value' => 'Dark Gray Leather'],
                ],
                'headline' => 'Futuristic Design & Superior Fuel Economy — 2023 Hyundai Tucson Hybrid',
                'description' => 'Geometric parametric hidden lights, roomy 5-passenger crossover cabin, and standard HTRAC AWD make this the ideal family adventure crossover.',
                'highlights' => [
                    ['type' => 'feature', 'title' => 'Fuel Economy', 'text' => 'Outstanding 38 MPG combined fuel economy with strong 226 horsepower hybrid punch.'],
                ],
                'equipment_list' => [
                    ['category' => 'Tech', 'items' => ['Hyundai SmartSense Safety', '10.25-inch Digital Cluster', 'Panoramic Sunroof', 'Bose Sound']],
                ],
                'seller' => [
                    'name' => 'SEOUL MOTORS DHAKA',
                    'role' => 'Korean Car Specialist',
                    'location' => 'Mirpur 10, Dhaka',
                    'phone' => '+880 1716-445566',
                    'rating' => '4.7',
                    'reviewsCount' => 39,
                    'memberSince' => '2021',
                ],
            ],
            [
                'slug' => 'kia-sportage-x-line-2023',
                'name' => '2023 Kia Sportage X-Line AWD Crossover',
                'brand' => 'Kia',
                'model' => 'Sportage',
                'year' => 2023,
                'condition' => 'Pre-Owned',
                'category' => 'popular,family',
                'asking_price' => '৳ 44,00,000',
                'price_lakh' => '44 Lakh Tk',
                'daily_price' => '1,700',
                'rating' => '4.8',
                'reviews' => '1,530',
                'passengers' => 5,
                'doors' => 4,
                'type' => 'Auto',
                'ac' => true,
                'location' => 'Mohakhali, Dhaka',
                'views' => 84,
                'published_date' => '25 Feb, 2024',
                'tag' => 'Smart SUV',
                'main_image' => '/images/corolla-cross-3.jpg',
                'is_featured' => true,
                'photos' => [
                    ['src' => '/images/corolla-cross-3.jpg', 'thumb' => '/images/corolla-cross-3.jpg', 'title' => 'Kia Sportage X-Line'],
                ],
                'key_specifications' => [
                    ['label' => 'Year', 'value' => '2023'],
                    ['label' => 'Condition', 'value' => 'Pre-Owned'],
                    ['label' => 'Engine', 'value' => '2.5L 4-Cylinder (187 HP)'],
                    ['label' => 'Fuel Type', 'value' => 'Octane'],
                    ['label' => 'Body Type', 'value' => 'Crossover'],
                    ['label' => 'Drive / Wheel', 'value' => 'Active AWD with Center Lock'],
                    ['label' => 'Mileage', 'value' => '15,000 km'],
                    ['label' => 'Transmission', 'value' => '8-Speed Automatic'],
                    ['label' => 'Color', 'value' => 'Jungle Green'],
                    ['label' => 'Interior', 'value' => 'Terracotta Two-Tone Leather'],
                ],
                'headline' => 'Bold & Versatile — 2023 Kia Sportage X-Line Crossover',
                'description' => 'Boomerang LED headlights, rugged X-Line cladding, and dual 12.3-inch panoramic curved displays for modern driving comfort.',
                'highlights' => [
                    ['type' => 'feature', 'title' => 'Rugged Styling', 'text' => 'Higher ground clearance, roof rack rails, matte black exterior trim, heated front seats.'],
                ],
                'equipment_list' => [
                    ['category' => 'Interior', 'items' => ['Dual Curved Panoramic Displays', 'Harman Kardon Premium Sound', 'Smart Power Tailgate', 'Blind Spot Monitor']],
                ],
                'seller' => [
                    'name' => 'PACIFIC AUTOMOBILES',
                    'role' => 'Certified Dealer',
                    'location' => 'Mohakhali C/A, Dhaka',
                    'phone' => '+880 1813-778899',
                    'rating' => '4.8',
                    'reviewsCount' => 43,
                    'memberSince' => '2019',
                ],
            ],
            [
                'slug' => 'ford-mustang-gt-convertible-2023',
                'name' => '2023 Ford Mustang GT Premium Convertible V8',
                'brand' => 'Ford',
                'model' => 'Mustang',
                'year' => 2023,
                'condition' => 'Certified Pre-Owned',
                'category' => 'luxury,popular',
                'asking_price' => '৳ 95,00,000',
                'price_lakh' => '95 Lakh Tk',
                'daily_price' => '2,400',
                'rating' => '4.8',
                'reviews' => '1,890',
                'passengers' => 4,
                'doors' => 2,
                'type' => 'Auto',
                'ac' => true,
                'location' => 'Gulshan 2, Dhaka',
                'views' => 170,
                'published_date' => '02 Mar, 2024',
                'tag' => 'Open Top Muscle',
                'main_image' => '/images/bmw-car.png',
                'is_featured' => true,
                'photos' => [
                    ['src' => '/images/bmw-car.png', 'thumb' => '/images/bmw-car.png', 'title' => 'Ford Mustang Convertible'],
                ],
                'key_specifications' => [
                    ['label' => 'Year', 'value' => '2023'],
                    ['label' => 'Condition', 'value' => 'Certified Pre-Owned'],
                    ['label' => 'Engine', 'value' => '5.0L Coyote V8 (450 HP)'],
                    ['label' => 'Fuel Type', 'value' => 'Octane'],
                    ['label' => 'Body Type', 'value' => 'Convertible'],
                    ['label' => 'Drive / Wheel', 'value' => 'RWD'],
                    ['label' => 'Mileage', 'value' => '10,500 km'],
                    ['label' => 'Transmission', 'value' => '10-Speed SelectShift Auto'],
                    ['label' => 'Color', 'value' => 'Velocity Blue Metallic'],
                    ['label' => 'Interior', 'value' => 'Ebony Leather with Heated/Cooled Seats'],
                ],
                'headline' => 'Roar of the Coyote V8 Under the Open Sky — 2023 Ford Mustang GT Convertible',
                'description' => 'Nothing matches the feeling of 450 naturally aspirated American V8 horsepower with the power soft-top folded away in seconds.',
                'highlights' => [
                    ['type' => 'feature', 'title' => 'Active Valve Exhaust', 'text' => 'Selectable quad-exhaust sound modes including Quiet, Normal, Sport, and Track.'],
                ],
                'equipment_list' => [
                    ['category' => 'Performance & Comfort', 'items' => ['MagneRide Damping System', 'Brembo 6-Piston Front Brakes', 'B&O 12-Speaker Sound System', 'Digital LCD Cluster']],
                ],
                'seller' => [
                    'name' => 'AMERICAN WHEELS BD',
                    'role' => 'Performance Dealer',
                    'location' => 'Gulshan 2, Dhaka',
                    'phone' => '+880 1718-990011',
                    'rating' => '4.8',
                    'reviewsCount' => 49,
                    'memberSince' => '2018',
                ],
            ],
            [
                'slug' => 'tesla-model-3-performance-2023',
                'name' => '2023 Tesla Model 3 Performance Dual Motor AWD',
                'brand' => 'Tesla',
                'model' => 'Model 3',
                'year' => 2023,
                'condition' => 'Pre-Owned',
                'category' => 'popular,luxury',
                'asking_price' => '৳ 82,00,000',
                'price_lakh' => '82 Lakh Tk',
                'daily_price' => '2,100',
                'rating' => '4.9',
                'reviews' => '2,310',
                'passengers' => 5,
                'doors' => 4,
                'type' => 'Auto',
                'ac' => true,
                'location' => 'Banani, Dhaka',
                'views' => 198,
                'published_date' => '28 Feb, 2024',
                'tag' => 'Pure Electric',
                'main_image' => '/images/hero-car.jpg',
                'is_featured' => true,
                'photos' => [
                    ['src' => '/images/hero-car.jpg', 'thumb' => '/images/hero-car.jpg', 'title' => 'Tesla Model 3 Performance'],
                ],
                'key_specifications' => [
                    ['label' => 'Year', 'value' => '2023'],
                    ['label' => 'Condition', 'value' => 'Pre-Owned'],
                    ['label' => 'Engine', 'value' => 'Dual Motor Electric AWD (455 HP)'],
                    ['label' => 'Fuel Type', 'value' => 'Electric (507 km Range)'],
                    ['label' => 'Body Type', 'value' => 'Sedan'],
                    ['label' => 'Drive / Wheel', 'value' => 'Dual Motor All-Wheel Drive'],
                    ['label' => 'Mileage', 'value' => '13,000 km'],
                    ['label' => 'Transmission', 'value' => 'Single-Speed Direct Drive'],
                    ['label' => 'Color', 'value' => 'Pearl White Multi-Coat'],
                    ['label' => 'Interior', 'value' => 'All Black Premium Vegan Leather'],
                ],
                'headline' => 'Instant Electric Torque — 2023 Tesla Model 3 Performance 0-100 in 3.1s',
                'description' => 'Supercar acceleration with whisper-quiet zero-emission refinement. Features Autopilot, Track Mode V2, and 20-inch Überturbine Wheels.',
                'highlights' => [
                    ['type' => 'feature', 'title' => 'Hyper Acceleration', 'text' => '0-100 km/h in 3.1 seconds, carbon fiber spoiler, performance brakes, lowered suspension.'],
                ],
                'equipment_list' => [
                    ['category' => 'Technology', 'items' => ['Autopilot Suite', '15-inch Touchscreen Infotainment', 'Premium Audio with Immersive Sound', 'Glass Roof']],
                ],
                'seller' => [
                    'name' => 'EV BANGLADESH',
                    'role' => 'Electric Vehicle Specialist',
                    'location' => 'Banani, Dhaka',
                    'phone' => '+880 1713-667788',
                    'rating' => '4.9',
                    'reviewsCount' => 61,
                    'memberSince' => '2021',
                ],
            ],
            [
                'slug' => 'audi-rs6-avant-performance-2023',
                'name' => '2023 Audi RS6 Avant Performance V8 Wagon',
                'brand' => 'Audi',
                'model' => 'RS6 Avant',
                'year' => 2023,
                'condition' => 'Certified Pre-Owned',
                'category' => 'luxury,family',
                'asking_price' => '৳ 1,90,00,000',
                'price_lakh' => '1.9 Crore Tk',
                'daily_price' => '2,900',
                'rating' => '5.0',
                'reviews' => '1,430',
                'passengers' => 5,
                'doors' => 5,
                'type' => 'Auto',
                'ac' => true,
                'location' => 'Gulshan 1, Dhaka',
                'views' => 140,
                'published_date' => '14 Mar, 2024',
                'tag' => 'Super Wagon',
                'main_image' => '/images/audi-car.jpg',
                'is_featured' => true,
                'photos' => [
                    ['src' => '/images/audi-car.jpg', 'thumb' => '/images/audi-car.jpg', 'title' => 'Audi RS6 Avant Wagon'],
                ],
                'key_specifications' => [
                    ['label' => 'Year', 'value' => '2023'],
                    ['label' => 'Condition', 'value' => 'Certified Pre-Owned'],
                    ['label' => 'Engine', 'value' => '4.0L Twin-Turbo V8 (621 HP)'],
                    ['label' => 'Fuel Type', 'value' => 'Octane / Mild Hybrid'],
                    ['label' => 'Body Type', 'value' => 'Wagon'],
                    ['label' => 'Drive / Wheel', 'value' => 'quattro All-Wheel Drive'],
                    ['label' => 'Mileage', 'value' => '7,500 km'],
                    ['label' => 'Transmission', 'value' => '8-Speed Tiptronic'],
                    ['label' => 'Color', 'value' => 'Nardo Gray'],
                    ['label' => 'Interior', 'value' => 'Valcona Leather with Honeycomb Stitching'],
                ],
                'headline' => 'The Ultimate High-Performance Estate — 2023 Audi RS6 Avant 621 HP',
                'description' => 'Unites supercar power with massive estate cargo room. 621 horsepower twin-turbo V8, quattro with sport differential, and RS adaptive air suspension.',
                'highlights' => [
                    ['type' => 'feature', 'title' => 'Super Wagon', 'text' => '0-100 in 3.4 seconds, widebody fenders, Bang & Olufsen Advanced 3D Sound, ceramic brakes.'],
                ],
                'equipment_list' => [
                    ['category' => 'Performance', 'items' => ['RS Adaptive Air Suspension', 'Dynamic All-Wheel Steering', 'Matrix LED with Laser Light', 'Sport Exhaust']],
                ],
                'seller' => [
                    'name' => 'EUROPEAN ELITE MOTORS',
                    'role' => 'Luxury Import Specialist',
                    'location' => 'Gulshan 1, Dhaka',
                    'phone' => '+880 1715-223344',
                    'rating' => '5.0',
                    'reviewsCount' => 70,
                    'memberSince' => '2017',
                ],
            ],
        ];

        foreach ($cars as $carData) {
            $brand = Brand::where('name', $carData['brand'])->first();
            $brandId = $brand?->id;

            $model = null;
            if ($brandId) {
                $model = CarModel::where('brand_id', $brandId)
                    ->where(function ($q) use ($carData) {
                        $q->where('name', $carData['model'])
                            ->orWhere('name', 'like', '%'.$carData['model'].'%');
                    })
                    ->first();
            }

            $carData['brand_id'] = $brandId;
            $carData['car_model_id'] = $model?->id;

            Car::updateOrCreate(
                ['slug' => $carData['slug']],
                $carData
            );
        }
    }
}
